In [4]:
import pandas as pd

path = '/home/abdul/sales-analytics-dashboard/data/raw/Sample - Superstore.csv'
df = pd.read_csv(path, encoding='latin-1')
print("Shape:", df.shape)

Shape: (9994, 21)

In [5]:
print(df.columns.tolist())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

In [6]:
print(df.dtypes)

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [7]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [8]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [9]:
# Total nulls per column
print("=== Missing Values ===")
print(df.isnull().sum())

print("\n=== Missing Percentage ===")
print((df.isnull().sum() / len(df) * 100).round(2))

=== Missing Values ===
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

=== Missing Percentage ===
Row ID           0.0
Order ID         0.0
Order Date       0.0
Ship Date        0.0
Ship Mode        0.0
Customer ID      0.0
Customer Name    0.0
Segment          0.0
Country          0.0
City             0.0
State            0.0
Postal Code      0.0
Region           0.0
Product ID       0.0
Category         0.0
Sub-Category     0.0
Product Name     0.0
Sales            0.0
Quantity         0.0
Discount         0.0
Profit           0.0
dtype: float64

In [10]:
print("Total rows:", len(df))
print("Duplicate rows:", df.duplicated().sum())

# If any duplicates found, remove them
df = df.drop_duplicates()
print("Rows after deduplication:", len(df))

Total rows: 9994
Duplicate rows: 0
Rows after deduplication: 9994

In [11]:
# Fix Order Date and Ship Date
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date']  = pd.to_datetime(df['Ship Date'])

# Fix Postal Code — must be string to preserve leading zeros
df['Postal Code'] = df['Postal Code'].astype(str)

# Confirm the fixes
print(df[['Order Date', 'Ship Date', 'Postal Code']].dtypes)
print("\nSample dates:")
print(df[['Order Date', 'Ship Date']].head(3))

Order Date     datetime64[us]
Ship Date      datetime64[us]
Postal Code               str
dtype: object

Sample dates:
  Order Date  Ship Date
0 2016-11-08 2016-11-11
1 2016-11-08 2016-11-11
2 2016-06-12 2016-06-16

In [12]:
#Feature Engineering
# How many days between order placed and order shipped?
df['Shipping Days'] = (df['Ship Date'] - df['Order Date']).dt.days

print("Shipping Days stats:")
print(df['Shipping Days'].describe())

Shipping Days stats:
count    9994.000000
mean        3.958175
std         1.747567
min         0.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         7.000000
Name: Shipping Days, dtype: float64

In [13]:
#Time column for trend analysis
df['Year']       = df['Order Date'].dt.year
df['Month']      = df['Order Date'].dt.month
df['Month Name'] = df['Order Date'].dt.strftime('%b')   # Jan, Feb, Mar...
df['YearMonth']  = df['Order Date'].dt.to_period('M').astype(str)  # 2014-01

print("Unique years in dataset:", sorted(df['Year'].unique()))
print("Sample YearMonth values:", df['YearMonth'].head(3).tolist())

Unique years in dataset: [np.int32(2014), np.int32(2015), np.int32(2016), np.int32(2017)]
Sample YearMonth values: ['2016-11', '2016-11', '2016-06']

In [14]:
#Profit margin 
# Profit as a percentage of Sales
df['Profit Margin %'] = (df['Profit'] / df['Sales'] * 100).round(2)

print("Profit Margin % stats:")
print(df['Profit Margin %'].describe())

Profit Margin % stats:
count    9994.000000
mean       12.031390
std        46.675436
min      -275.000000
25%         7.500000
50%        27.000000
75%        36.250000
max        50.000000
Name: Profit Margin %, dtype: float64

In [15]:
#Revenue tier(segmentation)
df['Revenue Tier'] = pd.cut(
    df['Sales'],
    bins=[0, 100, 500, 1000, 99999],
    labels=['Low', 'Medium', 'High', 'Very High']
)

print("\nRevenue Tier distribution:")
print(df['Revenue Tier'].value_counts())

Revenue Tier distribution:
Revenue Tier
Low          6229
Medium       2603
High          694
Very High     468
Name: count, dtype: int64

In [16]:
#verifying the cleaned dataset 
print("=== Final Shape ===")
print(df.shape)

print("\n=== All Columns ===")
print(df.columns.tolist())

print("\n=== Data Types ===")
print(df.dtypes)

print("\n=== Sample of new columns ===")
df[['Order Date', 'Shipping Days', 'Year', 'YearMonth', 'Profit Margin %', 'Revenue Tier']].head()

=== Final Shape ===
(9994, 28)

=== All Columns ===
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Shipping Days', 'Year', 'Month', 'Month Name', 'YearMonth', 'Profit Margin %', 'Revenue Tier']

=== Data Types ===
Row ID                      int64
Order ID                      str
Order Date         datetime64[us]
Ship Date          datetime64[us]
Ship Mode                     str
Customer ID                   str
Customer Name                 str
Segment                       str
Country                       str
City                          str
State                         str
Postal Code                   str
Region                        str
Product ID                    str
Category                      str
Sub-Category                  str
Product Name                  str
Sales                     float64
Quantity                    int64
Discount                  float64
Profit                    float64
Shipping Days               int64
Year                        int32
Month                       int32
Month Name                    str
YearMonth                     str
Profit Margin %           float64
Revenue Tier             category
dtype: object

=== Sample of new columns ===

  Order Date  Shipping Days  Year YearMonth  Profit Margin % Revenue Tier
0 2016-11-08              3  2016   2016-11            16.00       Medium
1 2016-11-08              3  2016   2016-11            30.00         High
2 2016-06-12              4  2016   2016-06            47.00          Low
3 2015-10-11              7  2015   2015-10           -40.00         High
4 2015-10-11              7  2015   2015-10            11.25          Low

In [17]:
CLEAN_DATA = '/home/abdul/sales-analytics-dashboard/data/processed/clean_superstore.csv'

df.to_csv(CLEAN_DATA, index=False)
print(f"✅ Clean data saved to: {CLEAN_DATA}")
print(f"   Rows: {len(df)}, Columns: {len(df.columns)}")

✅ Clean data saved to: /home/abdul/sales-analytics-dashboard/data/processed/clean_superstore.csv
   Rows: 9994, Columns: 28